# docker build -t youdaoyzbx/ymir-executor:ymir2.5.0-grounded-sam-huge-cu111-infer -f ymir/dockerfile .

FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime

WORKDIR /app
COPY . /app

RUN	sed -i 's#http://archive.ubuntu.com#https://mirrors.ustc.edu.cn#g' /etc/apt/sources.list \
    && sed -i 's#http://security.ubuntu.com#https://mirrors.ustc.edu.cn#g' /etc/apt/sources.list

RUN apt-get update && apt-get install --no-install-recommends ffmpeg=7:* \
    libsm6=2:* libxext6=2:* build-essential git \
    vim=2:* -y \
    && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# install ymir-exc sdk
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install "git+https://github.com/yzbx/ymir-executor-sdk.git@ymir2.1.0"

RUN pip install --no-cache-dir -e segment_anything && \
    pip install --no-cache-dir -e GroundingDINO && \
    pip install --no-cache-dir opencv-python==4.7.0.72 \
    pycocotools==2.0.6 matplotlib==3.5.3 \
    onnxruntime==1.14.1 onnx==1.13.1

RUN mkdir -p /img-man && mv /app/ymir/img-man/*.yaml /img-man/

RUN echo "python3 /app/ymir/start.py" > /usr/bin/start.sh
CMD bash /usr/bin/start.sh
